#define PCS__I_RF_RESET            1
#define PCS__I_RF_LOOPBACK            2
#define PCS__I_RF_IDLE_PATTERN_MODE                    3
#define PCS__I_RF_ENABLE_TX_AM_INSERTION               4
#define SCRAMBLER__I_RF_ENABLE                         5
#define SCRAMBLER__I_RF_BYPASS                         6
#define DESKEW__I_RF_ENABLE                            7
#define REORDER__I_RF_ENABLE                           8
#define REORDER__I_RF_RESET_ORDER                      9
#define DESCRAMBLER__I_RF_ENABLE                       10
#define DESCRAMBLER__I_RF_BYPASS                       11
#define DECODER__I_RF_ENABLE                           12
#define CHANNEL__I_RF_BIT_SKEW_BASE                    13
#define CHANNEL1__I_RF_BIT_SKEW                        14
#define CHANNEL2__I_RF_BIT_SKEW                        15
#define CHANNEL3__I_RF_BIT_SKEW                        16
#define CHANNEL4__I_RF_BIT_SKEW             17
#define CHANNEL5__I_RF_BIT_SKEW             18
#define CHANNEL6__I_RF_BIT_SKEW             19
#define CHANNEL7__I_RF_BIT_SKEW             20
#define CHANNEL8__I_RF_BIT_SKEW             21
#define CHANNEL9__I_RF_BIT_SKEW             22
#define CHANNEL10__I_RF_BIT_SKEW             23
#define CHANNEL11__I_RF_BIT_SKEW             24
#define CHANNEL12__I_RF_BIT_SKEW             25
#define CHANNEL13__I_RF_BIT_SKEW             26
#define CHANNEL14__I_RF_BIT_SKEW             27
#define CHANNEL15__I_RF_BIT_SKEW             28
#define CHANNEL16__I_RF_BIT_SKEW             29
#define CHANNEL17__I_RF_BIT_SKEW             30
#define CHANNEL18__I_RF_BIT_SKEW             31
#define CHANNEL19__I_RF_BIT_SKEW             32
#define CHANNEL__I_RF_UPDATE_PAYLOAD_BASE            33
#define CHANNEL1__I_RF_UPDATE_PAYLOAD            34
#define CHANNEL2__I_RF_UPDATE_PAYLOAD            35
#define CHANNEL3__I_RF_UPDATE_PAYLOAD            36
#define CHANNEL4__I_RF_UPDATE_PAYLOAD            37
#define CHANNEL5__I_RF_UPDATE_PAYLOAD            38
#define CHANNEL6__I_RF_UPDATE_PAYLOAD            39
#define CHANNEL7__I_RF_UPDATE_PAYLOAD            40
#define CHANNEL8__I_RF_UPDATE_PAYLOAD            41
#define CHANNEL9__I_RF_UPDATE_PAYLOAD            42
#define CHANNEL10__I_RF_UPDATE_PAYLOAD            43
#define CHANNEL11__I_RF_UPDATE_PAYLOAD            44
#define CHANNEL12__I_RF_UPDATE_PAYLOAD            45
#define CHANNEL13__I_RF_UPDATE_PAYLOAD            46
#define CHANNEL14__I_RF_UPDATE_PAYLOAD            47
#define CHANNEL15__I_RF_UPDATE_PAYLOAD            48
#define CHANNEL16__I_RF_UPDATE_PAYLOAD            49
#define CHANNEL17__I_RF_UPDATE_PAYLOAD            50
#define CHANNEL18__I_RF_UPDATE_PAYLOAD            51
#define CHANNEL19__I_RF_UPDATE_PAYLOAD            52
#define CHANNEL__I_RF_PAYLOAD_MODE            53
#define CHANNEL__I_RF_PAYLOAD_ERR_MASK            54
#define CHANNEL__I_RF_PAYLOAD_ERR_BURST            55
#define CHANNEL__I_RF_PAYLOAD_ERR_PERIOD            56
#define CHANNEL__I_RF_PAYLOAD_ERR_REPEAT            57
#define CHANNEL__I_RF_UPDATE_SHBREAKER_BASE            58
#define CHANNEL1__I_RF_UPDATE_SHBREAKER            59
#define CHANNEL2__I_RF_UPDATE_SHBREAKER            60
#define CHANNEL3__I_RF_UPDATE_SHBREAKER            61
#define CHANNEL4__I_RF_UPDATE_SHBREAKER            62
#define CHANNEL5__I_RF_UPDATE_SHBREAKER            63
#define CHANNEL6__I_RF_UPDATE_SHBREAKER            64
#define CHANNEL7__I_RF_UPDATE_SHBREAKER            65
#define CHANNEL8__I_RF_UPDATE_SHBREAKER            66
#define CHANNEL9__I_RF_UPDATE_SHBREAKER            67
#define CHANNEL10__I_RF_UPDATE_SHBREAKER            68
#define CHANNEL11__I_RF_UPDATE_SHBREAKER            69
#define CHANNEL12__I_RF_UPDATE_SHBREAKER            70
#define CHANNEL13__I_RF_UPDATE_SHBREAKER            71
#define CHANNEL14__I_RF_UPDATE_SHBREAKER            72
#define CHANNEL15__I_RF_UPDATE_SHBREAKER            73
#define CHANNEL16__I_RF_UPDATE_SHBREAKER            74
#define CHANNEL17__I_RF_UPDATE_SHBREAKER            75
#define CHANNEL18__I_RF_UPDATE_SHBREAKER            76
#define CHANNEL19__I_RF_UPDATE_SHBREAKER            77
#define CHANNEL__I_RF_SHBREAKER_MODE            78
#define CHANNEL__I_RF_SHBREAKER_ERR_MASK            79
#define CHANNEL__I_RF_SHBREAKER_ERR_BURST            80
#define CHANNEL__I_RF_SHBREAKER_ERR_PERIOD            81
#define CHANNEL__I_RF_SHBREAKER_ERR_REPEAT            82
#define CHANNEL__I_RF_UPDATE_BITSKEW_BASE            83
#define CHANNEL1__I_RF_UPDATE_BITSKEW            84
#define CHANNEL2__I_RF_UPDATE_BITSKEW            85
#define CHANNEL3__I_RF_UPDATE_BITSKEW            86
#define CHANNEL4__I_RF_UPDATE_BITSKEW            87
#define CHANNEL5__I_RF_UPDATE_BITSKEW            88
#define CHANNEL6__I_RF_UPDATE_BITSKEW            89
#define CHANNEL7__I_RF_UPDATE_BITSKEW            90
#define CHANNEL8__I_RF_UPDATE_BITSKEW            91
#define CHANNEL9__I_RF_UPDATE_BITSKEW            92
#define CHANNEL10__I_RF_UPDATE_BITSKEW            93
#define CHANNEL11__I_RF_UPDATE_BITSKEW            94
#define CHANNEL12__I_RF_UPDATE_BITSKEW            95
#define CHANNEL13__I_RF_UPDATE_BITSKEW            96
#define CHANNEL14__I_RF_UPDATE_BITSKEW            97
#define CHANNEL15__I_RF_UPDATE_BITSKEW            98
#define CHANNEL16__I_RF_UPDATE_BITSKEW            99
#define CHANNEL17__I_RF_UPDATE_BITSKEW            100
#define CHANNEL18__I_RF_UPDATE_BITSKEW            101
#define CHANNEL19__I_RF_UPDATE_BITSKEW            102
#define CHANNEL__I_RF_BIT_SKEW_INDEX            103
#define BLKSYNC__I_RF_ENABLE            104
#define ALIGNER__I_RF_ENABLE            105
#define DESKEWER__I_RF_ENABLE            106
#define REORDER__I_RF_ENABLE            107
#define DESCRAMBLER__I_RF_ENABLE            108
#define PTRNCHECK__I_RF_ENABLE            109
#define DECODER__I_RF_ENABLE            110
#define BLKSYNC__I_RF_LOCKED_TIMER_LIMIT            111
#define BLKSYNC__I_RF_UNLOCKED_TIMER_LIMIT            112
#define BLKSYNC__I_RF_SH_INVALID_LIMIT            113
#define ALIGNER__I_RF_INVALID_AM_THR            114
#define ALIGNER__I_RF_VALID_AM_THR            115
#define ALIGNER__I_RF_AM_PERIOD            116
#define REORDER__I_RF_RESET_ORDER            117
#define BERMONITOR__O_RF_HI_BER_BASE            118
#define BERMONITOR1__O_RF_HI_BER            119
#define BERMONITOR2__O_RF_HI_BER            120
#define BERMONITOR3__O_RF_HI_BER            121
#define BERMONITOR4__O_RF_HI_BER            122
#define BERMONITOR5__O_RF_HI_BER            123
#define BERMONITOR6__O_RF_HI_BER            124
#define BERMONITOR7__O_RF_HI_BER            125
#define BERMONITOR8__O_RF_HI_BER            126
#define BERMONITOR9__O_RF_HI_BER            127
#define BERMONITOR10__O_RF_HI_BER            128
#define BERMONITOR11__O_RF_HI_BER            129
#define BERMONITOR12__O_RF_HI_BER            130
#define BERMONITOR13__O_RF_HI_BER            131
#define BERMONITOR14__O_RF_HI_BER            132
#define BERMONITOR15__O_RF_HI_BER            133
#define BERMONITOR16__O_RF_HI_BER            134
#define BERMONITOR17__O_RF_HI_BER            135
#define BERMONITOR18__O_RF_HI_BER            136
#define BERMONITOR19__O_RF_HI_BER            137
#define BERMONITOR__I_RF_COR_HI_BER_BASE            138
#define BERMONITOR1__I_RF_COR_HI_BER            139
#define BERMONITOR2__I_RF_COR_HI_BER            140
#define BERMONITOR3__I_RF_COR_HI_BER            141
#define BERMONITOR4__I_RF_COR_HI_BER            142
#define BERMONITOR5__I_RF_COR_HI_BER            143
#define BERMONITOR6__I_RF_COR_HI_BER            144
#define BERMONITOR7__I_RF_COR_HI_BER            145
#define BERMONITOR8__I_RF_COR_HI_BER            146
#define BERMONITOR9__I_RF_COR_HI_BER            147
#define BERMONITOR10__I_RF_COR_HI_BER            148
#define BERMONITOR11__I_RF_COR_HI_BER            149
#define BERMONITOR12__I_RF_COR_HI_BER            150
#define BERMONITOR13__I_RF_COR_HI_BER            151
#define BERMONITOR14__I_RF_COR_HI_BER            152
#define BERMONITOR15__I_RF_COR_HI_BER            153
#define BERMONITOR16__I_RF_COR_HI_BER            154
#define BERMONITOR17__I_RF_COR_HI_BER            155
#define BERMONITOR18__I_RF_COR_HI_BER            156
#define BERMONITOR19__I_RF_COR_HI_BER            157
#define ALIGNER__O_RF_BIP_ERROR_COUNT_BASE            158
#define ALIGNER1__O_RF_BIP_ERROR_COUNT            159
#define ALIGNER2__O_RF_BIP_ERROR_COUNT            160
#define ALIGNER3__O_RF_BIP_ERROR_COUNT            161
#define ALIGNER4__O_RF_BIP_ERROR_COUNT            162
#define ALIGNER5__O_RF_BIP_ERROR_COUNT            163
#define ALIGNER6__O_RF_BIP_ERROR_COUNT            164
#define ALIGNER7__O_RF_BIP_ERROR_COUNT            165
#define ALIGNER8__O_RF_BIP_ERROR_COUNT            166
#define ALIGNER9__O_RF_BIP_ERROR_COUNT            167
#define ALIGNER10__O_RF_BIP_ERROR_COUNT            168
#define ALIGNER11__O_RF_BIP_ERROR_COUNT            169
#define ALIGNER12__O_RF_BIP_ERROR_COUNT            170
#define ALIGNER13__O_RF_BIP_ERROR_COUNT            171
#define ALIGNER14__O_RF_BIP_ERROR_COUNT            172
#define ALIGNER15__O_RF_BIP_ERROR_COUNT            173
#define ALIGNER16__O_RF_BIP_ERROR_COUNT            174
#define ALIGNER17__O_RF_BIP_ERROR_COUNT            175
#define ALIGNER18__O_RF_BIP_ERROR_COUNT            176
#define ALIGNER19__O_RF_BIP_ERROR_COUNT            177
#define ALIGNER__O_RF_RESYNC_COUNT_BASE            178
#define ALIGNER1__O_RF_RESYNC_COUNT            179
#define ALIGNER2__O_RF_RESYNC_COUNT            180
#define ALIGNER3__O_RF_RESYNC_COUNT            181
#define ALIGNER4__O_RF_RESYNC_COUNT            182
#define ALIGNER5__O_RF_RESYNC_COUNT            183
#define ALIGNER6__O_RF_RESYNC_COUNT            184
#define ALIGNER7__O_RF_RESYNC_COUNT            185
#define ALIGNER8__O_RF_RESYNC_COUNT            186
#define ALIGNER9__O_RF_RESYNC_COUNT            187
#define ALIGNER10__O_RF_RESYNC_COUNT            188
#define ALIGNER11__O_RF_RESYNC_COUNT            189
#define ALIGNER12__O_RF_RESYNC_COUNT            190
#define ALIGNER13__O_RF_RESYNC_COUNT            191
#define ALIGNER14__O_RF_RESYNC_COUNT            192
#define ALIGNER15__O_RF_RESYNC_COUNT            193
#define ALIGNER16__O_RF_RESYNC_COUNT            194
#define ALIGNER17__O_RF_RESYNC_COUNT            195
#define ALIGNER18__O_RF_RESYNC_COUNT            196
#define ALIGNER19__O_RF_RESYNC_COUNT            197
#define ALIGNER__O_RF_AM_LOCK_BASE            198
#define ALIGNER1__O_RF_AM_LOCK            199
#define ALIGNER2__O_RF_AM_LOCK            200
#define ALIGNER3__O_RF_AM_LOCK            201
#define ALIGNER4__O_RF_AM_LOCK            202
#define ALIGNER5__O_RF_AM_LOCK            203
#define ALIGNER6__O_RF_AM_LOCK            204
#define ALIGNER7__O_RF_AM_LOCK            205
#define ALIGNER8__O_RF_AM_LOCK            206
#define ALIGNER9__O_RF_AM_LOCK            207
#define ALIGNER10__O_RF_AM_LOCK            208
#define ALIGNER11__O_RF_AM_LOCK            209
#define ALIGNER12__O_RF_AM_LOCK            210
#define ALIGNER13__O_RF_AM_LOCK            211
#define ALIGNER14__O_RF_AM_LOCK            212
#define ALIGNER15__O_RF_AM_LOCK            213
#define ALIGNER16__O_RF_AM_LOCK            214
#define ALIGNER17__O_RF_AM_LOCK            215
#define ALIGNER18__O_RF_AM_LOCK            216
#define ALIGNER19__O_RF_AM_LOCK            217
#define DESKEWER__O_RF_INVALID_SKEW            218
#define PTRNCHECK__O_RF_MISMATCH_COUNT            219
#define BLKSYNC__O_RF_BLOCK_LOCK_BASE            220
#define BLKSYNC1__O_RF_BLOCK_LOCK            221
#define BLKSYNC2__O_RF_BLOCK_LOCK            222
#define BLKSYNC3__O_RF_BLOCK_LOCK            223
#define BLKSYNC4__O_RF_BLOCK_LOCK            224
#define BLKSYNC5__O_RF_BLOCK_LOCK            225
#define BLKSYNC6__O_RF_BLOCK_LOCK            226
#define BLKSYNC7__O_RF_BLOCK_LOCK            227
#define BLKSYNC8__O_RF_BLOCK_LOCK            228
#define BLKSYNC9__O_RF_BLOCK_LOCK            229
#define BLKSYNC10__O_RF_BLOCK_LOCK            230
#define BLKSYNC11__O_RF_BLOCK_LOCK            231
#define BLKSYNC12__O_RF_BLOCK_LOCK            232
#define BLKSYNC13__O_RF_BLOCK_LOCK            233
#define BLKSYNC14__O_RF_BLOCK_LOCK            234
#define BLKSYNC15__O_RF_BLOCK_LOCK            235
#define BLKSYNC16__O_RF_BLOCK_LOCK            236
#define BLKSYNC17__O_RF_BLOCK_LOCK            237
#define BLKSYNC18__O_RF_BLOCK_LOCK            238
#define BLKSYNC19__O_RF_BLOCK_LOCK            239
#define ALIGNER__O_RF_ID_BASE            240
#define ALIGNER1__O_RF_ID            241
#define ALIGNER2__O_RF_ID            242
#define ALIGNER3__O_RF_ID            243
#define ALIGNER4__O_RF_ID            244
#define ALIGNER5__O_RF_ID            245
#define ALIGNER6__O_RF_ID            246
#define ALIGNER7__O_RF_ID            247
#define ALIGNER8__O_RF_ID            248
#define ALIGNER9__O_RF_ID            249
#define ALIGNER10__O_RF_ID            250
#define ALIGNER11__O_RF_ID            251
#define ALIGNER12__O_RF_ID            252
#define ALIGNER13__O_RF_ID            253
#define ALIGNER14__O_RF_ID            254
#define ALIGNER15__O_RF_ID            255
#define ALIGNER16__O_RF_ID            256
#define ALIGNER17__O_RF_ID            257
#define ALIGNER18__O_RF_ID            258
#define ALIGNER19__O_RF_ID            259
#define BLKSYNCS__O_RF_BLOCK_LOCK            260
#define ALIGNERS__O_RF_ALIGN_LOCK            261
#define ALIGNER__O_RF_LANE_ID_BASE            262
#define ALIGNER1__O_RF_LANE_ID            263
#define ALIGNER2__O_RF_LANE_ID            264
#define ALIGNER3__O_RF_LANE_ID            265
#define ALIGNER4__O_RF_LANE_ID            266
#define ALIGNER5__O_RF_LANE_ID            267
#define ALIGNER6__O_RF_LANE_ID            268
#define ALIGNER7__O_RF_LANE_ID            269
#define ALIGNER8__O_RF_LANE_ID            270
#define ALIGNER9__O_RF_LANE_ID            271
#define ALIGNER10__O_RF_LANE_ID            272
#define ALIGNER11__O_RF_LANE_ID            273
#define ALIGNER12__O_RF_LANE_ID            274
#define ALIGNER13__O_RF_LANE_ID            275
#define ALIGNER14__O_RF_LANE_ID            276
#define ALIGNER15__O_RF_LANE_ID            277
#define ALIGNER16__O_RF_LANE_ID            278
#define ALIGNER17__O_RF_LANE_ID            279
#define ALIGNER18__O_RF_LANE_ID            280
#define ALIGNER19__O_RF_LANE_ID            281
#define ALIGNER__O_COR_LANE_ID            282
#define ALIGNER__O_RF_BIP_ERROR_BASE            283
#define ALIGNER1__O_RF_BIP_ERROR            284
#define ALIGNER2__O_RF_BIP_ERROR            285
#define ALIGNER3__O_RF_BIP_ERROR            286
#define ALIGNER4__O_RF_BIP_ERROR            287
#define ALIGNER5__O_RF_BIP_ERROR            288
#define ALIGNER6__O_RF_BIP_ERROR            289
#define ALIGNER7__O_RF_BIP_ERROR            290
#define ALIGNER8__O_RF_BIP_ERROR            291
#define ALIGNER9__O_RF_BIP_ERROR            292
#define ALIGNER10__O_RF_BIP_ERROR            293
#define ALIGNER11__O_RF_BIP_ERROR            294
#define ALIGNER12__O_RF_BIP_ERROR            295
#define ALIGNER13__O_RF_BIP_ERROR            296
#define ALIGNER14__O_RF_BIP_ERROR            297
#define ALIGNER15__O_RF_BIP_ERROR            298
#define ALIGNER16__O_RF_BIP_ERROR            299
#define ALIGNER17__O_RF_BIP_ERROR            300
#define ALIGNER18__O_RF_BIP_ERROR            301
#define ALIGNER19__O_RF_BIP_ERROR            302
#define ALIGNER__I_COR_BIP_ERROR_BASE            303
#define ALIGNER1__I_COR_BIP_ERROR            304
#define ALIGNER2__I_COR_BIP_ERROR            305
#define ALIGNER3__I_COR_BIP_ERROR            306
#define ALIGNER4__I_COR_BIP_ERROR            307
#define ALIGNER5__I_COR_BIP_ERROR            308
#define ALIGNER6__I_COR_BIP_ERROR            309
#define ALIGNER7__I_COR_BIP_ERROR            310
#define ALIGNER8__I_COR_BIP_ERROR            311
#define ALIGNER9__I_COR_BIP_ERROR            312
#define ALIGNER10__I_COR_BIP_ERROR            313
#define ALIGNER11__I_COR_BIP_ERROR            314
#define ALIGNER12__I_COR_BIP_ERROR            315
#define ALIGNER13__I_COR_BIP_ERROR            316
#define ALIGNER14__I_COR_BIP_ERROR            317
#define ALIGNER15__I_COR_BIP_ERROR            318
#define ALIGNER16__I_COR_BIP_ERROR            319
#define ALIGNER17__I_COR_BIP_ERROR            320
#define ALIGNER18__I_COR_BIP_ERROR            321
#define ALIGNER19__I_COR_BIP_ERROR            322
#define ALIGNER__O_RF_RESYNC_BASE            323
#define ALIGNER1__O_RF_RESYNC            324
#define ALIGNER2__O_RF_RESYNC            325
#define ALIGNER3__O_RF_RESYNC            326
#define ALIGNER4__O_RF_RESYNC            327
#define ALIGNER5__O_RF_RESYNC            328
#define ALIGNER6__O_RF_RESYNC            329
#define ALIGNER7__O_RF_RESYNC            330
#define ALIGNER8__O_RF_RESYNC            331
#define ALIGNER9__O_RF_RESYNC            332
#define ALIGNER10__O_RF_RESYNC            333
#define ALIGNER11__O_RF_RESYNC            334
#define ALIGNER12__O_RF_RESYNC            335
#define ALIGNER13__O_RF_RESYNC            336
#define ALIGNER14__O_RF_RESYNC            337
#define ALIGNER15__O_RF_RESYNC            338
#define ALIGNER16__O_RF_RESYNC            339
#define ALIGNER17__O_RF_RESYNC            340
#define ALIGNER18__O_RF_RESYNC            341
#define ALIGNER19__O_RF_RESYNC            342
#define DESKEW__O_RF_INVALID_SKEW            343
#define DESKEW__O_COR_INVALID_SKEW            344
#define TESTPATT__O_RF_ERROR_COUNTER            345
#define TESTPATT__O_COR_ERROR_COUNTER            346
#define DECODER__O_RF_ERROR_COUNTER            347
#define DECODER__O_COR_ERROR_COUNTER            348
